spring:
  datasource:
    url: jdbc:mysql://localhost:3306/research?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
logging:
  level:
    root: info